In [14]:
# External
import torch
import numpy as np


torch.manual_seed(42)
%load_ext rich

The rich extension is already loaded. To reload it, use:
  %reload_ext rich


In [8]:
print(torch.__version__)

2.6.0+cu124

In [9]:
x = torch.Tensor(2,3,4)
x


tensor([[[9.7250e-43, 4.4842e-44, 9.3609e-30, 0.0000e+00],
         [1.6409e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [9.7110e-43, 0.0000e+00, 9.3610e-30, 0.0000e+00]],

        [[1.6395e-42, 4.0638e-44, 0.0000e+00, 0.0000e+00],
         [9.7110e-43, 0.0000e+00, 9.3610e-30, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 9.3611e-30, 0.0000e+00]]])

In [10]:
x = torch.Tensor([[1,2],[3,4]])
x


tensor([[1., 2.],
        [3., 4.]])

In [12]:
x = torch.rand(2,3,4)
x


tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])

In [13]:
shape = x.shape
print("Shape: ",shape)

size = x.size()
print("Size:", size)

dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Shape: 
torch.Size([2, 3, 4])

Size:
torch.Size([2, 3, 4])

Size: 2 3 4

In [15]:
np_arr = np.array( [[1,2],[3,4]])
tensor = torch.from_numpy(np_arr)
tensor


tensor([[1, 2],
        [3, 4]])

In [16]:
tensor = torch.arange(10)
np_arr = tensor.numpy()
np_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)
y = x1+x2
x1,x2,y


(
    tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]),
    tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]]),
    tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])
)

In [18]:
x2.add_(x1)
x2


tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])

In [19]:
x = torch.arange(6)
x = x.view(2,3)
x


tensor([[0, 1, 2],
        [3, 4, 5]])

In [20]:
x = x.permute(1,0)
x


tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [21]:
x = torch.arange(6)
x = x.view(2,3)
W = torch.arange(9).view(3,3)
h = torch.matmul(x,W)
h


tensor([[15, 18, 21],
        [42, 54, 66]])

In [22]:
x = torch.arange(12).view(3,4)
x[:,1]

tensor([1, 5, 9])

In [23]:
x[:2,-1]

tensor([3, 7])

In [24]:
x[1:3,1]

tensor([5, 9])

In [26]:
x = torch.ones((3))
x,x.requires_grad

(tensor([1., 1., 1.]), False)

In [28]:
x.requires_grad_(True)
x

tensor([1., 1., 1.], requires_grad=True)

In [33]:
a = torch.arange(3,dtype=torch.float32,requires_grad=True)
b = (a+2)**2
c = b+3
y = c.mean()
y

tensor(12.6667, grad_fn=<MeanBackward0>)