In [1]:
import torch

/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


## 2.1 Scalars, Vectors, Matrices and Tensors

In [2]:
scalar = torch.tensor(3.14) # Scalar
scalar

tensor(3.1400)

In [3]:
vector = torch.tensor([1,2,3,4]) #vector
vector

tensor([1, 2, 3, 4])

In [4]:
matrices = torch.randint(100,(2,2)) # matrix
matrices

tensor([[92, 27],
        [78, 83]])

In [5]:
tensor = torch.randint(10,(2,2,2))
tensor

tensor([[[6, 1],
         [7, 0]],

        [[6, 0],
         [2, 0]]])

### Transpose

In [9]:
tr = torch.ones(5)
tr.transpose(-1,0)

tensor([1., 1., 1., 1., 1.])